import{a as u}from"./assets/vendor-bdb8a163.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="https://api.themoviedb.org",p="/3/trending/movie/week",m="9b2515cc3c50c20e84c19bb79f2b818d",a=document.querySelector(".js-movie-list"),g=document.querySelector(".js-guard");let c=1;const h={root:null,rootMargin:"0px",threshold:0},v=new IntersectionObserver(y,h);async function d(r){const{data:s}=await u(`${f}${p}`,{params:{page:r,api_key:m}});return s}function l(r){return r.map(({poster_path:s,release_date:n,original_title:o,vote_averange:e,id:t})=>`<li class="movie-card" data-id ='${t}'>
      <img src="https://image.tmdb.org/t/p/w300${s}" alt="${o}">
      <div class ="movie-info">
      <h3>${o}</h3>
            <p>Relise Date: ${n}</p>
            <p>Vote Averange: ${e}</p>
          </div>
        </li>`).join("")}d(c).then(r=>{a.insertAdjacentHTML("beforeend",l(r.results)),r.page<500&&v.observe(g)}).catch(r=>{alert(r.message)});function y(r,s){r.forEach(async n=>{if(n.isIntersecting){c+=1;try{const o=await d(c);a.insertAdjacentHTML("beforeend",l(o.results)),o.page>=500&&s.unobserve(n.target)}catch(o){alert(o.message)}}})}
//# sourceMappingURL=commonHelpers.js.map
